# Dependencies
markdown:      redcarpet
highlighter:      pygments

redcarpet:
  extensions: [with_toc_data]

# Permalinks
permalink:        none

# Site settings
title: Airline
email: rvesse@dotnetrdf.org
description: > 
  Annotation-driven Java framework for building powerful Git style CLIs in Java
baseurl: "/airline" 
url: "http://rvesse.github.io"
twitter_username: RobVesse
github_username:  rvesse
exclude: [ "scripts" ]

author:
  name:           "Rob Vesse"
  url:            https://twitter.com/RobVesse

# Custom vars
version:          2.1.1
dev_version:	"2.2.0-SNAPSHOT"

github:
  repo:           https://github.com/rvesse/airline
